slsa-framework/example-package

.github/workflows/e2e.go.yml
This starts building the e2e test for go.
This PR runs a job that always fails, to validate the logic. I'll update with a call to the re-usable workflow in a follow-up PR
=> ✨ e2e test for Go

.github/workflows/e2e.go.major.tag.main.config-ldflags-assets.slsa3.yml
On major tag push, create release, then create provenance
For adding to slsa-verifier tests. Will add RELEASE.md docs on using this workflow in slsa-verifier repo.
=> e2e: add workflow for pushing major tag

.github/workflows/e2e.generic.push.main.default.slsa2.yml, .github/workflows/e2e.generic.tag.main.default.slsa2.yml, .github/workflows/scripts/e2e-create-release.sh, .github/workflows/scripts/e2e-utils.sh, .github/workflows/scripts/e2e-verify-release.sh, .github/workflows/scripts/e2e-verify.common.sh, .github/workflows/scripts/e2e.generic.default.verify.sh, .github/workflows/scripts/e2e.go.default.verify.sh
Fixes #25 
Updates https://github.com/slsa-framework/slsa-github-generator/issues/28
Updates https://github.com/slsa-framework/slsa-github-generator/issues/195
Combines test code into common files and does some cleanup.
Also adds a e2e test for tags for the generic workflow
=> Add tag e2e test for generic workflow

.github/workflows/e2e.generic-bazel.push.main.default.slsa2.yml, .github/workflows/e2e.generic-bazel.schedule.main.default.slsa2.yml, .github/workflows/e2e.generic-bazel.tag.main.default.slsa2.yml, .github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa2.yml
I copied the existing `e2e.generic.*slsa2.yml` files and replaced to
steps in the build actions: `Setup Go` got replaced with `Setup
Bazelisk` and `Build artifact` got updated to use `bazelisk` (`bazel` in
the background) to build.
Fixes #39. Though, probably then we need to duplicate this for SLSA
level 3 actions too, but I didn't want to do this at the moment as it
would require duplicating too many actions. Maybe at a later time?
Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>
=> Add workflows for generic builder with Bazel.

.github/workflows/e2e.generic.tag.main.default.slsa2.yml, .github/workflows/e2e.generic.workflow_dispatch.main.default.slsa2.yml
Without this, it would have been the same as generic tag action.
CC @laurentsimon 
Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>
=> Fix duplication in generic workflow dispatch action.

.github/workflows/scripts/e2e.go.default.verify.sh
@laurentsimon Why was `-z` used here? it produces a warning like `-bash: warning: command substitution: ignored null byte in input` and I couldn't see a reason why it would be used.
=> remove -z option from grep

.github/workflows/scripts/e2e-create-release.sh
Updates the release creation script to use the major version from `DEFAULT_VERSION` defined in each e2e test workflow.
Instead of checking the body of each release for the file name, we check the major version of the release against the major version of `DEFAULT_VERSION`. This allows us to skip making an API call to get the release body and save us a lot of API calls that are made against the PAT quota.
Also updated the script to use the common semver parsing functions.
=> Update release creation script

.github/workflows/e2e.go.schedule.main.adversarial-invalidpath.yml
`compile-builder` needs to be true otherwise the workflow will fail with an "Invalid ref" error for being run from the main branch and potentially mask problems with the config-file path handling.
We want it to fail for the right reasons.
=> compile-builder in invalidpath test

.github/workflows/e2e.go.schedule.main.adversarial-binary-upload.slsa3.yml, .github/workflows/e2e.go.schedule.main.adversarial-build-provenance.slsa3.yml, .github/workflows/e2e.go.schedule.main.adversarial-build.slsa3.yml, .github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml, .github/workflows/e2e.go.tag.main.adversarial-asset-provenance.slsa3.yml
Adversarial tests seem to have been passing when they should fail but the tests haven't created issues because the jobs had incorrect conditionals. This PR fixes the conditionals but tests will likely continue to fail but at least now the issues will be created.
=> Fix adversarial test checks

.github/workflows/scripts/e2e.go.default.verify.sh
I misunderstood the GitTag check on #62 so this PR adds the `-z` option back.
This should fix https://github.com/slsa-framework/slsa-github-generator/issues/377
=> Fix GitTag check

.github/workflows/e2e.generic.release.main.default.slsa3.yml, .github/workflows/e2e.generic.schedule.main.default.slsa3.yml, .github/workflows/e2e.generic.tag.branch1.default.slsa3.yml, .github/workflows/e2e.generic.tag.main.default.slsa3.yml
[this e2e test run](https://github.com/slsa-framework/example-package/actions/runs/2607555368) did not create a bug because the provenance job was not checked at the end.
This PR adds checks for the `provenance` job in generic e2e test workflows.
=> Check provenance job result

.github/workflows/scripts/e2e-verify.common.sh
This prevents using broken minor patch versions of the verifier.
only merge pending https://github.com/slsa-framework/slsa-verifier/pull/143
=> feat: only test max patch verifier versions

.github/workflows/e2e.generic.release.main.default.slsa3.yml, .github/workflows/e2e.generic.schedule.main.default.slsa3.yml, .github/workflows/e2e.generic.tag.branch1.default.slsa3.yml, .github/workflows/e2e.generic.tag.main.default.slsa3.yml, .github/workflows/e2e.go.push.branch1.config-ldflags.slsa3.yml, .github/workflows/e2e.go.push.main.config-ldflags.slsa3.yml, .github/workflows/e2e.go.push.main.config-noldflags.slsa3.yml, .github/workflows/e2e.go.release.main.config-ldflags-assets-tag.slsa3.yml, .github/workflows/e2e.go.release.main.config-ldflags-assets.slsa3.yml, .github/workflows/e2e.go.release.main.config-ldflags-noassets.slsa3.yml, .github/workflows/e2e.go.schedule.main.config-ldflags-main-dir.slsa3.yml, .github/workflows/e2e.go.schedule.main.config-ldflags-main.slsa3.yml, .github/workflows/e2e.go.schedule.main.config-noldflags.slsa3.yml, .github/workflows/e2e.go.tag.branch1.config-ldflags-assets.slsa3.yml, .github/workflows/e2e.go.tag.main.config-ldflags-assets-tag.slsa3.yml, .github/workflows/e2e.go.tag.main.config-ldflags-assets.slsa3.yml, .github/workflows/e2e.go.tag.main.config-ldflags-noassets.slsa3.yml, .github/workflows/e2e.go.workflow_dispatch.branch1.config-ldflags.slsa3.yml, .github/workflows/e2e.go.workflow_dispatch.main.config-noldflags.slsa3.yml
slsa-verifier requires 1.18:
```
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading k8s.io/kube-openapi v0.0.0-20220124234850-424119656bbf
Error: ../../../go/pkg/mod/sigs.k8s.io/release-utils@v0.7.1/version/version.go:124:25: bi.Settings undefined (type *debug.BuildInfo has no field or method Settings)
note: module requires Go 1.18
```
see https://github.com/slsa-framework/example-package/runs/7306391193?check_suite_focus=true
=> chore: update go version

.github/workflows/e2e.container.workflow_dispatch.main.default.slsa3.yml, .github/workflows/e2e.container.workflow_dispatch.main.workflow_inputs.slsa3.yml, .github/workflows/e2e.gcb.workflow_dispatch.main.cloudbuild.slsa3.yml, .github/workflows/e2e.gcb.workflow_dispatch.main.dockerfile.slsa3.yml, .github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml, .github/workflows/e2e.generic.workflow_dispatch.main.default.slsa3.yml, .github/workflows/e2e.generic.workflow_dispatch.main.workflow_inputs.slsa3.yml, .github/workflows/e2e.go.workflow_dispatch.branch1.config-ldflags.slsa3.yml, .github/workflows/e2e.go.workflow_dispatch.main.config-noldflags.slsa3.yml, .github/workflows/e2e.go.workflow_dispatch.main.workflow_inputs.slsa3.yml
Fixes https://github.com/slsa-framework/example-package/issues/110
Adds actions write perms to the dispatch job so it can trigger a workflow run:
https://docs.github.com/rest/reference/actions#create-a-workflow-dispatch-event
=> fix: fix permissions on dispatch job

.github/workflows/e2e.installer-action.yml, .github/workflows/verifier-e2e.generic.workflow_dispatch.main.all.slsa3.yml, .github/workflows/verifier-e2e.go.workflow_dispatch.main.all.slsa3.yml
I couldn't find a way to use a matrix to pin the action version, so I've written out releases manually for now.
=> Add e2e test for slsa-verifier installer.

WORKSPACE
This is to enable merging Dependabot created #141. We need to merge both of these on the same day to ensure that the bazel build does not break.
Unfortunately, Dependabot does not know to update this at the same time as creating #141 (and similar).
See also #128 which was needed to fix the builds when #121 landed.
=> Bump go version in `WORKSPACE` file.

.github/workflows/e2e.gcb.tag.main.annotated-build.slsa3.yml, .github/workflows/e2e.go.tag.main.config-ldflags-assets-draft-tag.slsa3.yml, .github/workflows/scripts/e2e-create-release.sh, .github/workflows/scripts/e2e-utils.sh, .github/workflows/scripts/e2e.go.default.verify.sh, main.go
as we merged https://github.com/slsa-framework/slsa-github-generator/pull/1882, we need to test it requested by @ianlewis and @laurentsimon in https://github.com/slsa-framework/slsa-github-generator/issues/1476. So, this PR aims to create a test for draft-release support.
=> add draft-release support

.github/workflows/e2e.container.schedule.main.provenance-registry.slsa3.yml, .golangci.yml
cc: @laurentsimon Fixes Issue [#2981](https://github.com/slsa-framework/slsa-github-generator/issues/2981)
=> feat(e2e): provenance registry option for container generator

.github/workflows/e2e.container.schedule.main.provenance-registry.slsa3.yml
@ianlewis / @laurentsimon  Here is the PR that does:
- image pushed to `GHCR.io`
- provenance pushed to `docker.io` with username `laurentsimon` (**hardcoded**) and `${{ secrets.E2E_DOCKER_HUB_TOKEN }}`
- Both registries expect the `slsa-framework/<workflow-name>` as the `namespace/repository` to exist
- Doesn't support any deletion of images
=> Swap image and provenance registries

.github/workflows/e2e.container.schedule.main.provenance-registry.slsa3.yml
@laurentsimon This should probably fix the typo in the `registry` leading to error in https://github.com/slsa-framework/slsa-github-generator/issues/3024#issuecomment-1852568509
=> Fix provenance registry typo

.github/workflows/e2e.container.schedule.main.provenance-registry.slsa3.yml, .github/workflows/scripts/e2e-verify.common.sh, .github/workflows/scripts/e2e.container.default.verify.sh
refers: https://github.com/slsa-framework/slsa-verifier/issues/724 and https://github.com/slsa-framework/slsa-github-generator/pull/3099.
Deprecate exporting COSIGN_REPOSITORY for slsa-verifier during container provenance verification when the --provenance-repository is specified.
=> feat: use provenance-repository input for slsa-verifier

WORKSPACE
Followup to #303 to fix slsa-github-generator's e2e tests
- https://github.com/slsa-framework/slsa-github-generator/issues/3130
___
bazelbuild/rules_g 0.41.0 claims to support go1.21, but this Issue suggests that it doesn't work
* https://github.com/bazelbuild/rules_go/releases
* https://github.com/bazelbuild/rules_go/issues/3644
Looking at release notes, it's difficult to know for sure which release fixes the issue, but a collaborator claims that it should be fixed after Nov 24, 2023
* https://github.com/bazelbuild/rules_go/releases
* https://github.com/bazelbuild/rules_go/issues/3644#issuecomment-1826085491
bazel-gazelle adds support for go1.21
* https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.33.0
I was able to reproduce the same error on a local machine, without the new …
=> fix: upgrade bazel for go1.21

.github/workflows/e2e.gradle.workflow_dispatch.main.project-at-repo-root.slsa3.yml
Fixes the [`concurrency`](https://docs.github.com/en/actions/using-jobs/using-concurrency) for the `.github/workflows/e2e.gradle.workflow_dispatch.main.project-at-repo-root.slsa3.yml` test.
/cc @ramonpetgrave64
=> Fix concurrency for gradle test

.github/workflows/e2e.generic.schedule.main.adversarial-invalidpath.slsa3.yml, .github/workflows/e2e.generic.schedule.main.multi-uses.slsa3.yml, .github/workflows/e2e.generic.schedule.main.provenance-name.slsa3.yml
Fixes this e2e test to use the provenance-name input, not the deprecated attestation-name.
https://github.com/slsa-framework/example-package/actions/runs/8469402503/workflow
https://github.com/slsa-framework/slsa-github-generator/issues/3471
=> use provenance-name, not attestation-name

.github/workflows/scripts/e2e-verify.common.sh
Addresses https://github.com/slsa-framework/slsa-github-generator/issues/3002#issuecomment-2060304866
```
...
FAILED: SLSA verification failed: builderID does not match provenance: expected version 'v0.3', got ''
```
The GCB Builder ID for newer provenances now does not include the tag `@v0.3` under the `inTotoSlsaProvenanceV1 `.
- https://cloud.google.com/build/docs/securing-builds/view-build-provenance
We'll have to verify without the tag. Not including the tag is still compatible with slsa-verifier for older provenances.
Tested in a GCP cloud console
A helper script to debug, checking against the age of the build (index), and the tag the check.
Similar to our [e2e test ](https://github.com/slsa-framework/example-package/blob/2643b5de5feed274ccdfdf8b855adbeb673e15a7/.github/workflows/e2e …
=> fix: update the GCB builder ID

.github/workflows/verifier-e2e.all.workflow_dispatch.main.all.slsa3.yml
https://github.com/slsa-framework/slsa-github-generator/issues/3576
Next step in https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#update-verifier
=> chore: v2.0.0: update verifier e2e refs

.github/workflows/e2e.generic.tag.main.goreleaser-assets-multi-subjects.slsa3.yml
changes `--rm-dist` to `--clean`
- https://goreleaser.com/deprecations/#-rm-dist
=> fix: goreleaser deprecated option

.golangci.yml, main.go
This commit fixes two issues that were causing the `golangci-lint` job to fail.
The first issue was a `gosec` error in `main.go` that was being suppressed by a `nolint` comment. The file permissions for `os.WriteFile` were too permissive. This has been fixed by changing the permissions from `0o644` to `0o600`.
The second issue was that the `.golangci.yml` file was outdated and incompatible with newer versions of `golangci-lint`. This was causing the linter to fail with a cryptic exit code. The configuration file has been updated to remove deprecated and inactivated linters.
=> Fix golangci-lint errors
