- .github/workflows/e2e.go.yml
- go.mod
- go.sum
- main.go
See title.
Upon failure, this will create an issue on our repo, like https://github.com/slsa-framework/slsa-github-generator-go/issues/76
> ✨ Run e2e 

- .github/workflows/e2e.generic.push.main.default.slsa2.yml
This should fix https://github.com/slsa-framework/slsa-github-generator/issues/190
> Fix binary name

- .github/workflows/e2e.generic-bazel.push.main.default.slsa2.yml
- .github/workflows/e2e.generic-bazel.schedule.main.default.slsa2.yml
- .github/workflows/e2e.generic-bazel.tag.main.default.slsa2.yml
- .github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa2.yml
Action is https://github.com/marketplace/actions/setup-bazelisk
Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>
> Fix a copy-paste typo that breaks Bazel actions

- .github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
- .github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
- .github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
- .github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
- .github/workflows/e2e.generic.push.branch1.default.slsa3.yml
- .github/workflows/e2e.generic.push.main.default.slsa3.yml
- .github/workflows/e2e.generic.schedule.main.default.slsa3.yml
- .github/workflows/e2e.generic.tag.branch1.default.slsa3.yml
- .github/workflows/e2e.generic.tag.main.default.slsa3.yml
- .github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
- .github/workflows/e2e.generic.workflow_dispatch.main.default.slsa3.yml
- .github/workflows/e2e.go.push.branch1.config-ldflags.slsa3.yml
- .github/workflows/scripts/e2e-create-release.sh
- .github/workflows/scripts/e2e-push.sh
Updates https://github.com/slsa-framework/slsa-github-generator/issues/28
> Add branch tests for generic workflow

- .github/workflows/scripts/e2e-utils.sh
- .github/workflows/scripts/e2e-verify.common.sh
- .github/workflows/scripts/e2e.generic.default.verify.sh
- .github/workflows/scripts/e2e.go.default.verify.sh
Adds version number comparison utilities and allows verification over a slsa-verifier version range.
> Verifier version check

- .github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
- .github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
- .github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
- .github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
- .github/workflows/e2e.generic.push.branch1.default.slsa3.yml
- .github/workflows/e2e.generic.push.main.default.slsa3.yml
- .github/workflows/e2e.generic.schedule.main.default.slsa3.yml
- .github/workflows/e2e.generic.tag.branch1.default.slsa3.yml
- .github/workflows/e2e.generic.tag.main.default.slsa3.yml
- .github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
- .github/workflows/e2e.generic.workflow_dispatch.main.default.slsa3.yml
@laurentsimon FYI testing e2e tests without PAT
Related #52
> Remove PAT for generic workflow e2e tests

- .github/workflows/scripts/e2e-verify.common.sh
> Fix HEAD version check

- .github/workflows/e2e.generic.release.main.default.slsa3.yml
Fixes https://github.com/slsa-framework/slsa-github-generator/issues/384
> Add generic workflow tests for release trigger

- .github/workflows/scripts/e2e-create-release.sh
- .github/workflows/scripts/e2e-push.sh
- .github/workflows/scripts/e2e-report-failure.sh
- .github/workflows/scripts/e2e-report-success.sh
Fixes the use of PAT_TOKEN if it's uninitialized.
> Fix use of PAT_TOKEN

- .github/workflows/scripts/e2e-create-release.sh
@laurentsimon FYI
https://github.com/slsa-framework/slsa-github-generator/issues/377
> Add 'v' to release tag to make it semver

- .github/workflows/scripts/e2e-verify.common.sh
see title, somehow i forgot to add this change in https://github.com/slsa-framework/example-package/pull/80
> fix: verification with release branch

- .github/workflows/scripts/e2e.go.default.verify.sh
> fix: make min verifier version at v1.0

- .github/workflows/e2e.generic.schedule.main.attestation-name.slsa3.yml
- .github/workflows/e2e.generic.schedule.main.empty-attestation-name.slsa3.yml
Adds some basic e2e tests for the attestation-name input to the generic workflow.
Updates https://github.com/slsa-framework/slsa-github-generator/issues/500
> Add attestation-name tests

- .github/workflows/scripts/e2e.generic.default.verify.sh
Updating e2e test for https://github.com/slsa-framework/slsa-github-generator/issues/627
Should be merged after https://github.com/slsa-framework/slsa-github-generator/pull/628
> update generic buildType

- .github/workflows/scripts/e2e-verify.common.sh
fixes all the failures in the verify funcs: https://github.com/slsa-framework/slsa-github-generator/issues/683
cc @laurentsimon
> fix: fix path to install slsa-verifier

- .github/workflows/e2e.container.push.main.default.slsa3.yml
> add push e2e test for container workflow

- .github/workflows/e2e.container.workflow_dispatch.main.default.slsa3.yml
> Add workflow_dispatch e2e test for container wf

- .github/workflows/e2e.container.workflow_dispatch.main.workflow_inputs.slsa3.yml
- .github/workflows/e2e.generic.workflow_dispatch.main.workflow_inputs.slsa3.yml
- .github/workflows/e2e.go.workflow_dispatch.main.workflow_inputs.slsa3.yml
- .github/workflows/scripts/e2e-verify.common.sh
@laurentsimon will this close https://github.com/slsa-framework/slsa-verifier/issues/213?
if needed, i can add test for generic builders/container
> test: add testing for workflow_inputs

- .github/workflows/scripts/e2e-verify.common.sh
> fix: fix workflow input arg

- .github/workflows/scripts/e2e-verify.common.sh
Fixes https://github.com/slsa-framework/example-package/issues/97
> wip: feat: support new verifier args

- .github/workflows/scripts/e2e.generic.default.verify.sh
Signed-off-by: Ian Lewis <ianlewis@google.com>
> Fix asset check for multi-subjects

- .github/workflows/e2e.container.push.main.default.slsa3.yml
- .github/workflows/e2e.container.schedule.main.default.slsa3.yml
- .github/workflows/e2e.container.tag.main.default.slsa3.yml
- .github/workflows/e2e.container.workflow_dispatch.main.default.slsa3.yml
- .github/workflows/e2e.container.workflow_dispatch.main.workflow_inputs.slsa3.yml
Signed-off-by: Ian Lewis <ianlewis@google.com>
> Use E2E_CONTAINER_TOKEN for container e2e tests

- .github/workflows/scripts/e2e-verify.common.sh
> fix branch arg name in shell script

- .github/workflows/e2e.gcb.workflow_dispatch.main.default.slsa3.yml
- cloudbuild.yaml
> add initial cloudbuild workflow dispatch

- .github/workflows/e2e.gcb.workflow_dispatch.main.cloudbuild.slsa3.yml
- .github/workflows/e2e.gcb.workflow_dispatch.main.dockerfile.slsa3.yml
- .github/workflows/schedule.delete-old-releases.yml
- .github/workflows/scripts/e2e-create-release.sh
- .github/workflows/scripts/e2e-delete-old-releases.sh
Updates https://github.com/slsa-framework/slsa-github-generator/issues/728
Updates https://github.com/slsa-framework/slsa-github-generator/issues/738
Signed-off-by: Ian Lewis <ianlewis@google.com>
> Add workflow to delete old releases

- WORKSPACE
- go.mod
/cc @mihaimaruseac 
Signed-off-by: Ian Lewis <ianmlewis@gmail.com>
> Update Go toolchain to 1.18

- .github/workflows/README.md
> fix deadlink, typos

- .github/workflows/e2e.gradle.workflow_dispatch.main.default.slsa3.yml
- .github/workflows/e2e.maven.workflow_dispatch.main.default.slsa3.yml
Fixes #3 here: https://github.com/slsa-framework/slsa-github-generator/issues/2662
Depends on https://github.com/slsa-framework/slsa-github-generator/pull/2665 to work.
@laurentsimon
> make artifact name in java builders unique

- .github/workflows/e2e.container.schedule.main.provenance-registry.slsa3.yml
Fix to update provenance docker hub registry to personal account "laurentsimon" for comment https://github.com/slsa-framework/slsa-github-generator/issues/3024#issuecomment-1853012762
> Fix provenance dockerhub registry account

- e2e/gradle/workflow_dispatch/gradlew
Ignoring the shellcheck for this test file
> Fix shellcheck

- .github/workflows/e2e.delegator-generic.create.main.checkout.slsa3.yml
- .github/workflows/e2e.delegator-generic.create.main.default.slsa3.yml
- .github/workflows/e2e.delegator-generic.push.main.default.slsa3.yml
- .github/workflows/e2e.delegator-generic.release.main.default.slsa3.yml
- .github/workflows/e2e.delegator-generic.tag.main.default.slsa3.yml
- .github/workflows/e2e.delegator-generic.workflow_dispatch.branch1.checkout.slsa3.yml
- .github/workflows/e2e.delegator-generic.workflow_dispatch.branch1.default.slsa3.yml
- .github/workflows/e2e.delegator-generic.workflow_dispatch.main.checkout.slsa3.yml
- .github/workflows/e2e.delegator-generic.workflow_dispatch.main.default.slsa3.yml
- .github/workflows/verifier-e2e.all.workflow_dispatch.main.all.slsa3.yml
> Revert bumping local workflows to v3.0.0

- .github/workflows/e2e.container-based.workflow_dispatch.main.adversarial-verifier-binary.slsa3.yml
- .github/workflows/e2e.container.workflow_dispatch.main.adversarial-verifier-binary.slsa3.yml
- .github/workflows/e2e.generic.workflow_dispatch.main.adversarial-verifier-binary.slsa3.yml
- .github/workflows/e2e.go.workflow_dispatch.main.adversarial-verifier-binary.slsa3.yml
- .github/workflows/scripts/e2e-gradle-push.sh
- .github/workflows/scripts/e2e-maven-push.sh
Looked at the bottom of
https://github.com/slsa-framework/example-package/pull/315/files and implemented all of the suggestions
> Solve all the lint suggestions

- .github/workflows/e2e.generic.push.branch1.default.slsa3.yml
- .github/workflows/e2e.generic.push.main.default.slsa3.yml
- .github/workflows/e2e.generic.push.main.upload-tag-name.slsa3.yml
- .github/workflows/e2e.generic.release.main.default.slsa3.yml
- .github/workflows/e2e.generic.schedule.main.attestation-name.slsa3.yml
- .github/workflows/e2e.generic.schedule.main.default.slsa3.yml
- .github/workflows/e2e.generic.schedule.main.multi-subjects.slsa3.yml
- .github/workflows/e2e.generic.schedule.main.multi-uses.slsa3.yml
- .github/workflows/e2e.generic.tag.branch1.default.slsa3.yml
- .github/workflows/e2e.generic.tag.main.annotated.slsa3.yml
- .github/workflows/e2e.generic.tag.main.assets.slsa3.yml
- .github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
- .github/workflows/e2e.generic.workflow_dispatch.main.default.slsa3.yml
- .github/workflows/e2e.generic.workflow_dispatch.main.large-subjects.slsa3.yml
- .github/workflows/e2e.generic.workflow_dispatch.main.tagname.slsa3.yml
- .github/workflows/e2e.generic.workflow_dispatch.main.workflow_inputs.slsa3.yml
Followup to https://github.com/slsa-framework/slsa-github-generator/pull/3313
> fix: use provenance-name output

- .github/workflows/e2e.nodejs.create.main.default.slsa3.yml
- .github/workflows/e2e.nodejs.push.branch1.default.slsa3.yml
- .github/workflows/e2e.nodejs.push.main.adversarial.slsa3.yml
- .github/workflows/e2e.nodejs.push.main.custom_publish.slsa3.yml
- .github/workflows/e2e.nodejs.push.main.disttag.slsa3.yml
- .github/workflows/e2e.nodejs.push.main.node16.slsa3.yml
- .github/workflows/e2e.nodejs.push.main.node18.slsa3.yml
- .github/workflows/e2e.nodejs.release.main.default.slsa3.yml
- .github/workflows/e2e.nodejs.tag.main.default.slsa3.yml
- .github/workflows/e2e.nodejs.tag.main.unscoped.slsa3.yml
- .github/workflows/e2e.nodejs.workflow_dispatch.main.default.slsa3.yml
Changing actions/setup-node to sue node-version: 20.
Hopefully resolve these errors:
https://github.com/slsa-framework/slsa-github-generator/issues/3494
```
Run npm publish "${TARBALL_PATH}" --access=public --provenance-file="${PROVENANCE_PATH}"
npm notice 
npm notice 📦  @slsa-framework/e2e-nodejs-push-main-custom_publish-slsa3@0.0.258
npm notice === Tarball Contents === 
npm notice 259B dist/hello.d.ts    
npm notice 139B dist/hello.d.ts.map
npm notice 362B dist/hello.js      
npm notice 253B dist/index.d.ts    
npm notice 156B dist/index.d.ts.map
npm notice 427B dist/index.js      
npm notice 439B package.json       
npm notice === Tarball Details === 
npm notice name:          @slsa-framework/e2e-nodejs-push-main-custom_publish-slsa3           
npm notice version:       0.0.258 …
```
> use node 20

- .github/workflows/e2e.go.workflow_dispatch.main.adversarial-verifier-binary.slsa3.yml
next step in release process 
https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#go-builder-verifier-test
https://github.com/slsa-framework/slsa-github-generator/issues/3576
> chore: v2.0.0-rc.0: update adversarial test

- .github/workflows/e2e.container.workflow_dispatch.main.adversarial-verifier-binary.slsa3.yml
https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#generic-generator-verifier-test
> chore: v2.0.0-rc.0: update adversarial test: generic_generator

- .github/workflows/e2e.generic.workflow_dispatch.main.adversarial-verifier-binary.slsa3.yml
https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#generic-generator-verifier-test
> chore: v2.0.0-rc.0: update adversarial test: generic generator

- .github/workflows/e2e.generic.workflow_dispatch.main.adversarial-verifier-binary.slsa3.yml
Reverts slsa-framework/example-package#353
> Revert "chore: v2.0.0-rc.0: update adversarial test: generic generator"

- .github/workflows/e2e.container-based.workflow_dispatch.main.adversarial-verifier-binary.slsa3.yml
https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#container-based-builder-verifier-test
> chore: v2.0.0-rc.0: update adversarial test: builder container based

- .github/workflows/e2e.container.workflow_dispatch.main.adversarial-builder-binary.slsa3.yml
Reverts slsa-framework/example-package#359
> Revert "chore: v2.0.0-rc.0: update adversarial test: Adversarial container ge…"

- .github/workflows/e2e.go.workflow_dispatch.main.adversarial-builder-binary.slsa3.yml
https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#adversarial-go-builder
> chore: v2.0.0-rc.0: update adversarial test: Adversarial Go builde

- .github/workflows/e2e.generic.workflow_dispatch.main.adversarial-builder-binary.slsa3.yml
https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#generic-generator-verifier-test
> chore: v2.0.0: update adversarial test: Adversarial generic generator

- .github/workflows/e2e.container.workflow_dispatch.main.adversarial-builder-binary.slsa3.yml
https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#adversarial-container-generator
> chore: v2.0.0: update adversarial test: Adversarial container generator

- .github/workflows/e2e.container-based.workflow_dispatch.main.adversarial-builder-binary.slsa3.yml
https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#adversarial-container-based-builder
> chore: v2.0.0-rc.0: update adversarial test: Adversarial container-based
